apiVersion: v1
kind: Pod
metadata:
  name: javaweb-calculator
  spec:
   containers:
      - name: javaweb-calculator
        image: ojeranti08/k8s-javaweb-calculator:latest
        ports:
        - containerPort: 8080