---
apiVersion: v1
kind: Service
metadata:
  name: K8S-JavaWeb3-service
  labels:
    app: K8S-JavaWeb3
spec:
  type: NodePort
  selector:
    app: K8S-JavaWeb3
  ports:
  - protocol: TCP
    port: 8080
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: K8S-JavaWeb3-deployment
spec:
  selector:
    matchLabels:
      app: K8S-JavaWeb3
  replicas: 1
  template:
    metadata:
      labels:
        app: K8S-JavaWeb3
    spec:
      containers:
      - name: K8S-JavaWeb3-container
        image: ojeranti08/K8S-JavaWeb3:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "0.5"  # Set the desired CPU limit
            memory: "512Mi"  # Set the desired memory limit
          requests:
            cpu: "0.2"  # Set the desired CPU request
            memory: "256Mi"  # Set the desired memory request
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8085
          initialDelaySeconds: 30
          timeoutSeconds: 1