apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaweb-calculator
  labels:
    app: javaweb-calculator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: javaweb-calculator
  template:
    metadata:
      labels:
        app: javaweb-calculator
      spec:
       containers:
       - name: javaweb-calculator
         image: ojeranti08/k8s-javaweb-calculator:latest
         ports:
         - containerPort: 8080