apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-javaweb3-deployment-v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-javaweb3-nexus
  template:
    metadata:
      labels:
        app: k8s-javaweb3-nexus
    spec:
      containers:
      - name: nexus-container
        image: binary-nexus
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8081
          initialDelaySeconds: 30
          timeoutSeconds: 2
    volumeMounts:
    - name: registry-secret-volume
      mountPath: /etc/docker/certs.d/https://hub.docker.com/repositories/ojeranti08
volumes:
- name: registry-secret-volume
  secret:
    secretName: my-registry-secret