apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: k8s-javaweb3
spec:
  replicas: 2
  selector:
    matchLabels:
      app:  k8s-javaweb3
  template:
    metadata:
      labels:
        app:  k8s-javaweb3
    spec:
      containers:
      - name:  k8s-javaweb3
        image: ojeranti08/k8s-javaweb3:latest
        ports:
        - containerPort: 8080
