apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-javaweb3-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-javaweb3
  template:
    metadata:
      labels:
        app: k8s-javaweb3
    spec:
      containers:
      - name: k8s-javaweb3-container
        image: ojeranti08/k8s-javaweb3:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 1

---
apiVersion: v1
kind: Service
metadata:
  name: k8s-javaweb3-service
  labels:
    app: k8s-javaweb3
spec:
  type: NodePort
  selector:
    app: k8s-javaweb3
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
