apiVersion: v1
kind: Service
metadata:
  name: k8s-javaweb3-service
  labels:
    app: k8s-javaweb3
spec:
  type: ClusterIP
  selector:
    app: k8s-javaweb3
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: httpd
