apiVersion: v1
kind: Service
metadata:
  name: k8s-javaweb3-service
  labels:
    app: k8s-javaweb3
spec:
  type: NodePort
  selector:
    app: k8s-javaweb3
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
