apiVersion: v1
kind: Deployment
metadata:
  name: k8s-javaweb3-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-javaweb3-nexus
  template:
    metadata:
      labels:
        app: k8s-javaweb3
    spec:
      containers:
      - name: nexus
        image: ojeranti08/k8s-javaweb3:latest
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8081
          initialDelaySeconds: 30
          timeoutSeconds: 2